import { useState } from 'react'
import { Search, Filter } from 'lucide-react'

function AlertTable({
  alerts = [],
  loading = false,
  onSelectAlert,
}) {
  const [search, setSearch] = useState('')
  const [severity, setSeverity] = useState('ALL')
  const [threat, setThreat] = useState('ALL')

  const filteredAlerts = alerts.filter((alert) => {
    const searchText = search.toLowerCase()

    const matchesSearch =
      alert.alert_id.toLowerCase().includes(searchText) ||
      alert.threat_class.toLowerCase().includes(searchText) ||
      alert.source.ip.toLowerCase().includes(searchText) ||
      alert.destination.ip.toLowerCase().includes(searchText)

    const matchesSeverity =
      severity === 'ALL' ||
      alert.severity === severity

    const matchesThreat =
      threat === 'ALL' ||
      alert.threat_class === threat

    return (
      matchesSearch &&
      matchesSeverity &&
      matchesThreat
    )
  })

  return (
    <section className="alerts-card">
      <div className="alerts-header">
        <div>
          <h2>Live Security Alerts</h2>
          <p>
            Security events generated by the threat detection engine
          </p>
        </div>

        <span className="demo-badge">
          BACKEND DATA
        </span>
      </div>

      <div className="alert-filters">
        <div className="search-box">
          <Search size={16} />

          <input
            type="text"
            placeholder="Search alert ID, IP, or threat..."
            value={search}
            onChange={(event) =>
              setSearch(event.target.value)
            }
          />
        </div>

        <div className="filter-control">
          <Filter size={15} />

          <select
            value={severity}
            onChange={(event) =>
              setSeverity(event.target.value)
            }
          >
            <option value="ALL">All Severity</option>
            <option value="CRITICAL">Critical</option>
            <option value="HIGH">High</option>
            <option value="MEDIUM">Medium</option>
            <option value="LOW">Low</option>
          </select>
        </div>

        <div className="filter-control">
          <select
            value={threat}
            onChange={(event) =>
              setThreat(event.target.value)
            }
          >
            <option value="ALL">All Threats</option>
            <option value="DDoS">DDoS</option>
            <option value="Port Scan">Port Scan</option>
            <option value="Brute Force">Brute Force</option>
            <option value="Data Exfiltration">
              Data Exfiltration
            </option>
            <option value="Suspicious DNS">
              Suspicious DNS
            </option>
            <option value="C2 Communication">
              C2 Communication
            </option>
            <option value="SSE Test Threat">
              SSE Test Threat
            </option>
            <option value="Manual Test Threat">
              Manual Test Threat
            </option>
            <option value="Live Verification">
              Live Verification
            </option>
          </select>
        </div>
      </div>

      <div className="alerts-result-count">
        {loading
          ? 'Loading backend alerts...'
          : `Showing ${filteredAlerts.length} of ${alerts.length} alerts`}
      </div>

      <div className="alerts-table-wrapper">
        <table className="alerts-table">
          <thead>
            <tr>
              <th>Alert ID</th>
              <th>Time</th>
              <th>Threat</th>
              <th>Severity</th>
              <th>Confidence</th>
              <th>Source</th>
              <th>Destination</th>
              <th>Protocol</th>
              <th>Method</th>
              <th>Status</th>
            </tr>
          </thead>

          <tbody>
            {loading ? (
              <tr>
                <td
                  colSpan="10"
                  className="no-alerts"
                >
                  Loading security alerts...
                </td>
              </tr>
            ) : filteredAlerts.length > 0 ? (
              filteredAlerts.map((alert) => (
                <tr
                  key={alert.alert_id}
                  className="alert-row"
                  onClick={() =>
                    onSelectAlert(alert)
                  }
                >
                  <td className="alert-id">
                    {alert.alert_id}
                  </td>

                  <td>
                    {new Date(
                      alert.timestamp
                    ).toLocaleTimeString()}
                  </td>

                  <td>
                    {alert.threat_class}
                  </td>

                  <td>
                    <span
                      className={`severity-badge ${alert.severity.toLowerCase()}`}
                    >
                      {alert.severity}
                    </span>
                  </td>

                  <td>
                    {(
                      alert.confidence * 100
                    ).toFixed(0)}
                    %
                  </td>

                  <td>
                    {alert.source.ip}:
                    {alert.source.port}
                  </td>

                  <td>
                    {alert.destination.ip}:
                    {alert.destination.port}
                  </td>

                  <td>
                    {alert.protocol}
                  </td>

                  <td>
                    {alert.detection_method.join(', ')}
                  </td>

                  <td>
                    <span className="status-badge">
                      {alert.status}
                    </span>
                  </td>
                </tr>
              ))
            ) : (
              <tr>
                <td
                  colSpan="10"
                  className="no-alerts"
                >
                  No alerts match the selected filters.
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </section>
  )
}

export default AlertTable