"""
M1 — CIC-IDS 2017 Flow Record
================================
Dataclass mapping the 78 pre-extracted features from the
CIC-IDS 2017 dataset (generated by CICFlowMeter).

Dataset files (drop into data/cic-ids-2017/):
  Monday-WorkingHours.pcap_ISCX.csv         ← Benign only
  Tuesday-WorkingHours.pcap_ISCX.csv        ← FTP-Patator, SSH-Patator
  Wednesday-WorkingHours.pcap_ISCX.csv      ← DoS (Slowloris, Hulk, GoldenEye, Heartbleed)
  Thursday-WorkingHours-Morning-*.csv       ← Web Attacks
  Thursday-WorkingHours-Afternoon-*.csv     ← Infiltration
  Friday-WorkingHours-Morning.pcap_ISCX.csv ← Botnet
  Friday-WorkingHours-Afternoon-DDos.csv    ← DDoS
  Friday-WorkingHours-Afternoon-PortScan.csv← PortScan
"""

from dataclasses import dataclass, field
from typing import Optional
import hashlib
import time as _time


# ── CIC-IDS 2017 column name → normalised Python attribute name ──────────────
# The dataset has inconsistent spacing/capitalisation across files.
# We normalise on load.

COLUMN_MAP = {
    # Identity
    "Flow ID":                     "flow_id_raw",
    "Source IP":                   "src_ip",
    "Source Port":                 "src_port",
    "Destination IP":              "dst_ip",
    "Destination Port":            "dst_port",
    "Protocol":                    "protocol_num",
    "Timestamp":                   "timestamp_str",
    # Volume
    "Flow Duration":               "flow_duration",
    "Total Fwd Packets":           "total_fwd_pkts",
    "Total Backward Packets":      "total_bwd_pkts",
    "Total Length of Fwd Packets": "fwd_bytes",
    "Total Length of Bwd Packets": "bwd_bytes",
    # Packet length stats
    "Fwd Packet Length Max":       "fwd_pkt_len_max",
    "Fwd Packet Length Min":       "fwd_pkt_len_min",
    "Fwd Packet Length Mean":      "fwd_pkt_len_mean",
    "Fwd Packet Length Std":       "fwd_pkt_len_std",
    "Bwd Packet Length Max":       "bwd_pkt_len_max",
    "Bwd Packet Length Min":       "bwd_pkt_len_min",
    "Bwd Packet Length Mean":      "bwd_pkt_len_mean",
    "Bwd Packet Length Std":       "bwd_pkt_len_std",
    # Flow-level rates
    "Flow Bytes/s":                "flow_bytes_s",
    "Flow Packets/s":              "flow_pkts_s",
    # Inter-arrival times
    "Flow IAT Mean":               "flow_iat_mean",
    "Flow IAT Std":                "flow_iat_std",
    "Flow IAT Max":                "flow_iat_max",
    "Flow IAT Min":                "flow_iat_min",
    "Fwd IAT Total":               "fwd_iat_total",
    "Fwd IAT Mean":                "fwd_iat_mean",
    "Fwd IAT Std":                 "fwd_iat_std",
    "Fwd IAT Max":                 "fwd_iat_max",
    "Fwd IAT Min":                 "fwd_iat_min",
    "Bwd IAT Total":               "bwd_iat_total",
    "Bwd IAT Mean":                "bwd_iat_mean",
    "Bwd IAT Std":                 "bwd_iat_std",
    "Bwd IAT Max":                 "bwd_iat_max",
    "Bwd IAT Min":                 "bwd_iat_min",
    # TCP Flags
    "Fwd PSH Flags":               "fwd_psh_flags",
    "Bwd PSH Flags":               "bwd_psh_flags",
    "Fwd URG Flags":               "fwd_urg_flags",
    "Bwd URG Flags":               "bwd_urg_flags",
    "FIN Flag Count":              "fin_flag_count",
    "SYN Flag Count":              "syn_flag_count",
    "RST Flag Count":              "rst_flag_count",
    "PSH Flag Count":              "psh_flag_count",
    "ACK Flag Count":              "ack_flag_count",
    "URG Flag Count":              "urg_flag_count",
    "CWE Flag Count":              "cwe_flag_count",
    "ECE Flag Count":              "ece_flag_count",
    # Header lengths
    "Fwd Header Length":           "fwd_header_len",
    "Bwd Header Length":           "bwd_header_len",
    "Fwd Header Length.1":         "fwd_header_len_1",  # duplicate col in dataset
    # Rates
    "Fwd Packets/s":               "fwd_pkts_s",
    "Bwd Packets/s":               "bwd_pkts_s",
    # Packet length aggregates
    "Min Packet Length":           "min_pkt_len",
    "Max Packet Length":           "max_pkt_len",
    "Packet Length Mean":          "pkt_len_mean",
    "Packet Length Std":           "pkt_len_std",
    "Packet Length Variance":      "pkt_len_var",
    # Misc
    "Down/Up Ratio":               "down_up_ratio",
    "Average Packet Size":         "avg_pkt_size",
    "Avg Fwd Segment Size":        "avg_fwd_seg_size",
    "Avg Bwd Segment Size":        "avg_bwd_seg_size",
    # Bulk transfer features
    "Fwd Avg Bytes/Bulk":          "fwd_avg_bytes_bulk",
    "Fwd Avg Packets/Bulk":        "fwd_avg_pkts_bulk",
    "Fwd Avg Bulk Rate":           "fwd_avg_bulk_rate",
    "Bwd Avg Bytes/Bulk":          "bwd_avg_bytes_bulk",
    "Bwd Avg Packets/Bulk":        "bwd_avg_pkts_bulk",
    "Bwd Avg Bulk Rate":           "bwd_avg_bulk_rate",
    # Subflow
    "Subflow Fwd Packets":         "subflow_fwd_pkts",
    "Subflow Fwd Bytes":           "subflow_fwd_bytes",
    "Subflow Bwd Packets":         "subflow_bwd_pkts",
    "Subflow Bwd Bytes":           "subflow_bwd_bytes",
    # Window sizes
    "Init_Win_bytes_forward":      "init_win_fwd",
    "Init_Win_bytes_backward":     "init_win_bwd",
    "act_data_pkt_fwd":            "act_data_pkt_fwd",
    "min_seg_size_forward":        "min_seg_size_fwd",
    # Active/Idle stats
    "Active Mean":                 "active_mean",
    "Active Std":                  "active_std",
    "Active Max":                  "active_max",
    "Active Min":                  "active_min",
    "Idle Mean":                   "idle_mean",
    "Idle Std":                    "idle_std",
    "Idle Max":                    "idle_max",
    "Idle Min":                    "idle_min",
    # Ground truth label
    "Label":                       "label",
}

# Protocol number → name
PROTO_NAMES = {0: "HOPOPT", 1: "ICMP", 6: "TCP", 17: "UDP", 58: "ICMPv6"}

# CIC-IDS 2017 label → our threat class
LABEL_TO_THREAT = {
    "BENIGN":                      None,
    "DoS Hulk":                    "DDOS",
    "PortScan":                    "RECON",
    "DDoS":                        "DDOS",
    "DoS GoldenEye":               "DDOS",
    "FTP-Patator":                 "RECON",
    "SSH-Patator":                 "RECON",
    "DoS slowloris":               "DDOS",
    "DoS Slowhttptest":            "DDOS",
    "Heartbleed":                  "TLS_ANOMALY",
    "Web Attack \x96 Brute Force": "RECON",
    "Web Attack – Brute Force":    "RECON",
    "Web Attack \x96 XSS":        "RECON",
    "Web Attack – XSS":            "RECON",
    "Web Attack \x96 Sql Injection": "RECON",
    "Web Attack – Sql Injection":  "RECON",
    "Infiltration":                "EXFIL",
    "Bot":                         "BEACON",
}


def _safe_float(v: str) -> float:
    try:
        f = float(v)
        return 0.0 if f != f else f   # handle NaN
    except (ValueError, TypeError):
        return 0.0


def _safe_int(v: str) -> int:
    try:
        return int(float(v))
    except (ValueError, TypeError):
        return 0


@dataclass
class CICFlowRecord:
    """
    One row from the CIC-IDS 2017 dataset.
    Ingested timestamp is set to wall-clock time when the row is streamed.
    """
    # ── Identity ──────────────────────────────────────────────────────────────
    flow_id:        str   = ""
    src_ip:         str   = ""
    src_port:       int   = 0
    dst_ip:         str   = ""
    dst_port:       int   = 0
    protocol:       str   = "TCP"
    timestamp_str:  str   = ""
    ingested_at:    float = field(default_factory=_time.time)

    # ── Volume ────────────────────────────────────────────────────────────────
    flow_duration:  float = 0.0   # microseconds
    total_fwd_pkts: int   = 0
    total_bwd_pkts: int   = 0
    fwd_bytes:      float = 0.0
    bwd_bytes:      float = 0.0

    # ── Packet length stats ───────────────────────────────────────────────────
    fwd_pkt_len_max:  float = 0.0
    fwd_pkt_len_min:  float = 0.0
    fwd_pkt_len_mean: float = 0.0
    fwd_pkt_len_std:  float = 0.0
    bwd_pkt_len_max:  float = 0.0
    bwd_pkt_len_min:  float = 0.0
    bwd_pkt_len_mean: float = 0.0
    bwd_pkt_len_std:  float = 0.0

    # ── Flow rates ─────────────────────────────────────────────────────────────
    flow_bytes_s:   float = 0.0
    flow_pkts_s:    float = 0.0
    fwd_pkts_s:     float = 0.0
    bwd_pkts_s:     float = 0.0

    # ── IAT ───────────────────────────────────────────────────────────────────
    flow_iat_mean:  float = 0.0
    flow_iat_std:   float = 0.0
    flow_iat_max:   float = 0.0
    flow_iat_min:   float = 0.0
    fwd_iat_mean:   float = 0.0
    fwd_iat_std:    float = 0.0
    bwd_iat_mean:   float = 0.0
    bwd_iat_std:    float = 0.0

    # ── TCP Flags ─────────────────────────────────────────────────────────────
    fin_flag_count: int   = 0
    syn_flag_count: int   = 0
    rst_flag_count: int   = 0
    psh_flag_count: int   = 0
    ack_flag_count: int   = 0
    urg_flag_count: int   = 0

    # ── Packet length aggregates ──────────────────────────────────────────────
    min_pkt_len:    float = 0.0
    max_pkt_len:    float = 0.0
    pkt_len_mean:   float = 0.0
    pkt_len_std:    float = 0.0

    # ── Derived ratios ─────────────────────────────────────────────────────────
    down_up_ratio:  float = 0.0
    avg_pkt_size:   float = 0.0
    init_win_fwd:   int   = 0
    init_win_bwd:   int   = 0
    active_mean:    float = 0.0
    idle_mean:      float = 0.0

    # ── Ground truth ──────────────────────────────────────────────────────────
    label:          str   = "BENIGN"
    threat_class:   str   = ""      # mapped from label

    @classmethod
    def from_row(cls, row: dict) -> "CICFlowRecord":
        """
        Parse a normalised CSV row dict into a CICFlowRecord.
        `row` keys are already normalised via COLUMN_MAP.
        """
        proto_num = _safe_int(row.get("protocol_num", "6"))
        label     = row.get("label", "BENIGN").strip()

        # Build a stable flow_id from the 5-tuple
        five_tuple = "|".join([
            row.get("src_ip", ""),
            row.get("dst_ip", ""),
            row.get("src_port", ""),
            row.get("dst_port", ""),
            str(proto_num),
        ])
        flow_id = hashlib.sha256(five_tuple.encode()).hexdigest()[:16]

        return cls(
            flow_id        = flow_id,
            src_ip         = row.get("src_ip", "").strip(),
            src_port       = _safe_int(row.get("src_port", "0")),
            dst_ip         = row.get("dst_ip", "").strip(),
            dst_port       = _safe_int(row.get("dst_port", "0")),
            protocol       = PROTO_NAMES.get(proto_num, str(proto_num)),
            timestamp_str  = row.get("timestamp_str", "").strip(),
            ingested_at    = _time.time(),

            flow_duration  = _safe_float(row.get("flow_duration", "0")),
            total_fwd_pkts = _safe_int(row.get("total_fwd_pkts", "0")),
            total_bwd_pkts = _safe_int(row.get("total_bwd_pkts", "0")),
            fwd_bytes      = _safe_float(row.get("fwd_bytes", "0")),
            bwd_bytes      = _safe_float(row.get("bwd_bytes", "0")),

            fwd_pkt_len_max  = _safe_float(row.get("fwd_pkt_len_max", "0")),
            fwd_pkt_len_min  = _safe_float(row.get("fwd_pkt_len_min", "0")),
            fwd_pkt_len_mean = _safe_float(row.get("fwd_pkt_len_mean", "0")),
            fwd_pkt_len_std  = _safe_float(row.get("fwd_pkt_len_std", "0")),
            bwd_pkt_len_max  = _safe_float(row.get("bwd_pkt_len_max", "0")),
            bwd_pkt_len_min  = _safe_float(row.get("bwd_pkt_len_min", "0")),
            bwd_pkt_len_mean = _safe_float(row.get("bwd_pkt_len_mean", "0")),
            bwd_pkt_len_std  = _safe_float(row.get("bwd_pkt_len_std", "0")),

            flow_bytes_s   = _safe_float(row.get("flow_bytes_s", "0")),
            flow_pkts_s    = _safe_float(row.get("flow_pkts_s", "0")),
            fwd_pkts_s     = _safe_float(row.get("fwd_pkts_s", "0")),
            bwd_pkts_s     = _safe_float(row.get("bwd_pkts_s", "0")),

            flow_iat_mean  = _safe_float(row.get("flow_iat_mean", "0")),
            flow_iat_std   = _safe_float(row.get("flow_iat_std", "0")),
            flow_iat_max   = _safe_float(row.get("flow_iat_max", "0")),
            flow_iat_min   = _safe_float(row.get("flow_iat_min", "0")),
            fwd_iat_mean   = _safe_float(row.get("fwd_iat_mean", "0")),
            fwd_iat_std    = _safe_float(row.get("fwd_iat_std", "0")),
            bwd_iat_mean   = _safe_float(row.get("bwd_iat_mean", "0")),
            bwd_iat_std    = _safe_float(row.get("bwd_iat_std", "0")),

            fin_flag_count = _safe_int(row.get("fin_flag_count", "0")),
            syn_flag_count = _safe_int(row.get("syn_flag_count", "0")),
            rst_flag_count = _safe_int(row.get("rst_flag_count", "0")),
            psh_flag_count = _safe_int(row.get("psh_flag_count", "0")),
            ack_flag_count = _safe_int(row.get("ack_flag_count", "0")),
            urg_flag_count = _safe_int(row.get("urg_flag_count", "0")),

            min_pkt_len    = _safe_float(row.get("min_pkt_len", "0")),
            max_pkt_len    = _safe_float(row.get("max_pkt_len", "0")),
            pkt_len_mean   = _safe_float(row.get("pkt_len_mean", "0")),
            pkt_len_std    = _safe_float(row.get("pkt_len_std", "0")),

            down_up_ratio  = _safe_float(row.get("down_up_ratio", "0")),
            avg_pkt_size   = _safe_float(row.get("avg_pkt_size", "0")),
            init_win_fwd   = _safe_int(row.get("init_win_fwd", "0")),
            init_win_bwd   = _safe_int(row.get("init_win_bwd", "0")),
            active_mean    = _safe_float(row.get("active_mean", "0")),
            idle_mean      = _safe_float(row.get("idle_mean", "0")),

            label          = label,
            threat_class   = LABEL_TO_THREAT.get(label, "UNKNOWN") or "",
        )

    def to_feature_dict(self) -> dict:
        """Return a flat dict of all numeric features for ML classifiers."""
        total_pkts = max(self.total_fwd_pkts + self.total_bwd_pkts, 1)
        total_bytes = self.fwd_bytes + self.bwd_bytes
        dur_sec = self.flow_duration / 1_000_000.0  # µs → seconds

        return {
            # Identity
            "flow_id":       self.flow_id,
            "src_ip":        self.src_ip,
            "dst_ip":        self.dst_ip,
            "src_port":      self.src_port,
            "dst_port":      self.dst_port,
            "protocol":      self.protocol,
            # Volume
            "pkt_count":     total_pkts,
            "byte_count":    total_bytes,
            "fwd_bytes":     self.fwd_bytes,
            "bwd_bytes":     self.bwd_bytes,
            "duration":      dur_sec,
            # Rates (CIC pre-computed)
            "flow_bytes_s":  self.flow_bytes_s,
            "flow_pkts_s":   self.flow_pkts_s,
            "bytes_per_sec": self.flow_bytes_s,
            "pkts_per_sec":  self.flow_pkts_s,
            # Packet size
            "mean_pkt_size": self.pkt_len_mean,
            "std_pkt_size":  self.pkt_len_std,
            "min_pkt_len":   self.min_pkt_len,
            "max_pkt_len":   self.max_pkt_len,
            # IAT
            "mean_iat":      self.flow_iat_mean,
            "std_iat":       self.flow_iat_std,
            # TCP flags (ratios)
            "syn_ratio":     self.syn_flag_count / total_pkts,
            "ack_ratio":     self.ack_flag_count / total_pkts,
            "rst_ratio":     self.rst_flag_count / total_pkts,
            "fin_ratio":     self.fin_flag_count / total_pkts,
            "psh_ratio":     self.psh_flag_count / total_pkts,
            "syn_count":     self.syn_flag_count,
            "ack_count":     self.ack_flag_count,
            "syn_no_ack":    int(self.syn_flag_count > 0 and self.ack_flag_count == 0),
            # Direction
            "down_up_ratio": self.down_up_ratio,
            "outbound_ratio": self.fwd_bytes / max(total_bytes, 1),
            # Window
            "init_win_fwd":  self.init_win_fwd,
            "init_win_bwd":  self.init_win_bwd,
            # Active/Idle
            "active_mean":   self.active_mean,
            "idle_mean":     self.idle_mean,
            # Ground truth (kept for evaluation)
            "label":         self.label,
            "threat_class":  self.threat_class,
        }

    @property
    def is_attack(self) -> bool:
        return self.label != "BENIGN"
