"""
Module 2 (M2) — Feature Schema & Mapping Specification
======================================================
Defines the mapping between NFStream native flow statistics, window packet metrics,
and the project / CIC-IDS 2017 schema consumed by downstream AI modules (M3/M4).
"""

from typing import Dict, List, Tuple

# Direct 1-to-1 Column Renaming (NFStream -> CIC-IDS 2017 / Project schema)
DIRECT_FEATURE_MAP: Dict[str, str] = {
    # Volume
    "src2dst_packets": "Total Fwd Packets",
    "dst2src_packets": "Total Backward Packets",
    "src2dst_bytes": "Total Length of Fwd Packets",
    "dst2src_bytes": "Total Length of Bwd Packets",
    # Packet length statistics
    "src2dst_max_ps": "Fwd Packet Length Max",
    "src2dst_min_ps": "Fwd Packet Length Min",
    "src2dst_mean_ps": "Fwd Packet Length Mean",
    "src2dst_stddev_ps": "Fwd Packet Length Std",
    "dst2src_max_ps": "Bwd Packet Length Max",
    "dst2src_min_ps": "Bwd Packet Length Min",
    "dst2src_mean_ps": "Bwd Packet Length Mean",
    "dst2src_stddev_ps": "Bwd Packet Length Std",
    # Packet length aggregates
    "bidirectional_min_ps": "Min Packet Length",
    "bidirectional_max_ps": "Max Packet Length",
    "bidirectional_mean_ps": "Packet Length Mean",
    "bidirectional_stddev_ps": "Packet Length Std",
    # TCP Flags
    "bidirectional_fin_packets": "FIN Flag Count",
    "bidirectional_syn_packets": "SYN Flag Count",
    "bidirectional_rst_packets": "RST Flag Count",
    "bidirectional_psh_packets": "PSH Flag Count",
    "bidirectional_ack_packets": "ACK Flag Count",
    "bidirectional_urg_packets": "URG Flag Count",
    "bidirectional_cwr_packets": "CWE Flag Count",
    "bidirectional_ece_packets": "ECE Flag Count",
    "src2dst_psh_packets": "Fwd PSH Flags",
    "dst2src_psh_packets": "Bwd PSH Flags",
    "src2dst_urg_packets": "Fwd URG Flags",
    "dst2src_urg_packets": "Bwd URG Flags",
}

# Metadata columns to preserve
META_COLUMNS: List[str] = [
    "window_id",
    "src_ip",
    "dst_ip",
    "src_port",
    "dst_port",
    "protocol",
    "protocol_name",
]

# Native NFStream DPI & Volume features kept for high-resolution detection
ENRICHED_COLUMNS: List[str] = [
    "bidirectional_duration_ms",
    "bidirectional_packets",
    "bidirectional_bytes",
    "src2dst_packets",
    "src2dst_bytes",
    "dst2src_packets",
    "dst2src_bytes",
    "application_name",
    "application_category_name",
    "application_confidence",
]

# Standard Deterministic Column Ordering for M2 Output DataFrame (82 columns)
DETERMINISTIC_COLUMN_ORDER: List[str] = [
    # Metadata
    "window_id",
    "src_ip",
    "dst_ip",
    "src_port",
    "dst_port",
    "protocol",
    "protocol_name",
    # Flow Duration
    "Flow Duration",
    # Volume
    "Total Fwd Packets",
    "Total Backward Packets",
    "Total Length of Fwd Packets",
    "Total Length of Bwd Packets",
    # Packet length stats
    "Fwd Packet Length Max",
    "Fwd Packet Length Min",
    "Fwd Packet Length Mean",
    "Fwd Packet Length Std",
    "Bwd Packet Length Max",
    "Bwd Packet Length Min",
    "Bwd Packet Length Mean",
    "Bwd Packet Length Std",
    "Min Packet Length",
    "Max Packet Length",
    "Packet Length Mean",
    "Packet Length Std",
    "Packet Length Variance",
    "Average Packet Size",
    "Avg Fwd Segment Size",
    "Avg Bwd Segment Size",
    # Rates
    "Flow Bytes/s",
    "Flow Packets/s",
    "Fwd Packets/s",
    "Bwd Packets/s",
    # IAT stats
    "Flow IAT Mean",
    "Flow IAT Std",
    "Flow IAT Max",
    "Flow IAT Min",
    "Fwd IAT Total",
    "Fwd IAT Mean",
    "Fwd IAT Std",
    "Fwd IAT Max",
    "Fwd IAT Min",
    "Bwd IAT Total",
    "Bwd IAT Mean",
    "Bwd IAT Std",
    "Bwd IAT Max",
    "Bwd IAT Min",
    # TCP Flags
    "FIN Flag Count",
    "SYN Flag Count",
    "RST Flag Count",
    "PSH Flag Count",
    "ACK Flag Count",
    "URG Flag Count",
    "CWE Flag Count",
    "ECE Flag Count",
    "Fwd PSH Flags",
    "Bwd PSH Flags",
    "Fwd URG Flags",
    "Bwd URG Flags",
    # Cumulative TCP Flag Bitmask
    "tcp_flag_bitmask",
    # Ratios
    "Down/Up Ratio",
    # TTL Features
    "TTL Mean",
    "TTL Std",
    "TTL Variance",
    "TTL Min",
    "TTL Max",
    # TCP Window Features
    "TCP Window Size Init",
    "TCP Window Size Mean",
    # IP Fragment Flags
    "IP Flags DF Count",
    "IP Flags MF Count",
    # Retransmission
    "Retransmission Count",
    # Port Access Pattern
    "Port Sequentiality Score",
    "Port Access Type",
    # Enriched DPI / NFStream details
    "bidirectional_duration_ms",
    "bidirectional_packets",
    "bidirectional_bytes",
    "src2dst_packets",
    "src2dst_bytes",
    "dst2src_packets",
    "dst2src_bytes",
    "application_name",
    "application_category_name",
    "application_confidence",
]

# Strict target dtypes
SCHEMA_DTYPES: Dict[str, str] = {
    "window_id": "string",
    "src_ip": "string",
    "dst_ip": "string",
    "src_port": "int64",
    "dst_port": "int64",
    "protocol": "int64",
    "protocol_name": "string",
    "Flow Duration": "float64",
    "Total Fwd Packets": "int64",
    "Total Backward Packets": "int64",
    "Total Length of Fwd Packets": "float64",
    "Total Length of Bwd Packets": "float64",
    "Fwd Packet Length Max": "float64",
    "Fwd Packet Length Min": "float64",
    "Fwd Packet Length Mean": "float64",
    "Fwd Packet Length Std": "float64",
    "Bwd Packet Length Max": "float64",
    "Bwd Packet Length Min": "float64",
    "Bwd Packet Length Mean": "float64",
    "Bwd Packet Length Std": "float64",
    "Min Packet Length": "float64",
    "Max Packet Length": "float64",
    "Packet Length Mean": "float64",
    "Packet Length Std": "float64",
    "Packet Length Variance": "float64",
    "Average Packet Size": "float64",
    "Avg Fwd Segment Size": "float64",
    "Avg Bwd Segment Size": "float64",
    "Flow Bytes/s": "float64",
    "Flow Packets/s": "float64",
    "Fwd Packets/s": "float64",
    "Bwd Packets/s": "float64",
    "Flow IAT Mean": "float64",
    "Flow IAT Std": "float64",
    "Flow IAT Max": "float64",
    "Flow IAT Min": "float64",
    "Fwd IAT Total": "float64",
    "Fwd IAT Mean": "float64",
    "Fwd IAT Std": "float64",
    "Fwd IAT Max": "float64",
    "Fwd IAT Min": "float64",
    "Bwd IAT Total": "float64",
    "Bwd IAT Mean": "float64",
    "Bwd IAT Std": "float64",
    "Bwd IAT Max": "float64",
    "Bwd IAT Min": "float64",
    "FIN Flag Count": "int64",
    "SYN Flag Count": "int64",
    "RST Flag Count": "int64",
    "PSH Flag Count": "int64",
    "ACK Flag Count": "int64",
    "URG Flag Count": "int64",
    "CWE Flag Count": "int64",
    "ECE Flag Count": "int64",
    "Fwd PSH Flags": "int64",
    "Bwd PSH Flags": "int64",
    "Fwd URG Flags": "int64",
    "Bwd URG Flags": "int64",
    "tcp_flag_bitmask": "int64",
    "Down/Up Ratio": "float64",
    "TTL Mean": "float64",
    "TTL Std": "float64",
    "TTL Variance": "float64",
    "TTL Min": "float64",
    "TTL Max": "float64",
    "TCP Window Size Init": "float64",
    "TCP Window Size Mean": "float64",
    "IP Flags DF Count": "int64",
    "IP Flags MF Count": "int64",
    "Retransmission Count": "int64",
    "Port Sequentiality Score": "float64",
    "Port Access Type": "string",
    "bidirectional_duration_ms": "int64",
    "bidirectional_packets": "int64",
    "bidirectional_bytes": "int64",
    "src2dst_packets": "int64",
    "src2dst_bytes": "int64",
    "dst2src_packets": "int64",
    "dst2src_bytes": "int64",
    "application_name": "string",
    "application_category_name": "string",
    "application_confidence": "int64",
}

# Documentation / audit records for feature mapping with Master Guide classifications:
# Category A: Genuinely extracted from NFStream
# Category B: Correctly derived from packet/flow data
# Category C: Extracted via window packet analyzer
# Category D: Genuinely unsupported / limitation
FEATURE_DOCUMENTATION: List[Tuple[str, str, str, str, str, str]] = [
    # (NFStream / Source, Project Feature, Target Dtype, Category, Derivation, Notes)
    ("bidirectional_duration_ms", "Flow Duration", "float64", "B", "val * 1000.0", "Converted from ms to µs for CIC-IDS 2017"),
    ("src2dst_packets", "Total Fwd Packets", "int64", "A", "Direct 1:1", "Total packets in forward direction"),
    ("dst2src_packets", "Total Backward Packets", "int64", "A", "Direct 1:1", "Total packets in backward direction"),
    ("src2dst_bytes", "Total Length of Fwd Packets", "float64", "A", "Direct 1:1", "Total payload bytes in forward direction"),
    ("dst2src_bytes", "Total Length of Bwd Packets", "float64", "A", "Direct 1:1", "Total payload bytes in backward direction"),
    ("src2dst_max_ps", "Fwd Packet Length Max", "float64", "A", "Direct 1:1", "Maximum packet size in forward direction"),
    ("src2dst_min_ps", "Fwd Packet Length Min", "float64", "A", "Direct 1:1", "Minimum packet size in forward direction"),
    ("src2dst_mean_ps", "Fwd Packet Length Mean", "float64", "A", "Direct 1:1", "Mean packet size in forward direction"),
    ("src2dst_stddev_ps", "Fwd Packet Length Std", "float64", "A", "Direct 1:1", "Std deviation of packet size in forward direction"),
    ("dst2src_max_ps", "Bwd Packet Length Max", "float64", "A", "Direct 1:1", "Maximum packet size in backward direction"),
    ("dst2src_min_ps", "Bwd Packet Length Min", "float64", "A", "Direct 1:1", "Minimum packet size in backward direction"),
    ("dst2src_mean_ps", "Bwd Packet Length Mean", "float64", "A", "Direct 1:1", "Mean packet size in backward direction"),
    ("dst2src_stddev_ps", "Bwd Packet Length Std", "float64", "A", "Direct 1:1", "Std deviation of packet size in backward direction"),
    ("bidirectional_min_ps", "Min Packet Length", "float64", "A", "Direct 1:1", "Overall minimum packet length"),
    ("bidirectional_max_ps", "Max Packet Length", "float64", "A", "Direct 1:1", "Overall maximum packet length"),
    ("bidirectional_mean_ps", "Packet Length Mean", "float64", "A", "Direct 1:1", "Overall mean packet length"),
    ("bidirectional_stddev_ps", "Packet Length Std", "float64", "A", "Direct 1:1", "Overall packet length standard deviation"),
    ("bidirectional_stddev_ps", "Packet Length Variance", "float64", "B", "val ** 2", "Variance computed as square of standard deviation"),
    ("bidirectional_mean_ps", "Average Packet Size", "float64", "A", "Direct 1:1", "Equivalent to overall mean packet size"),
    ("src2dst_mean_ps", "Avg Fwd Segment Size", "float64", "A", "Direct 1:1", "Equivalent to forward mean packet size"),
    ("dst2src_mean_ps", "Avg Bwd Segment Size", "float64", "A", "Direct 1:1", "Equivalent to backward mean packet size"),
    ("bidirectional_bytes, duration", "Flow Bytes/s", "float64", "B", "bytes / max(dur_sec, 0.001)", "Flow throughput in bytes per second"),
    ("bidirectional_packets, duration", "Flow Packets/s", "float64", "B", "pkts / max(dur_sec, 0.001)", "Flow packet rate per second"),
    ("src2dst_packets, duration", "Fwd Packets/s", "float64", "B", "fwd_pkts / max(dur_sec, 0.001)", "Forward packet rate per second"),
    ("dst2src_packets, duration", "Bwd Packets/s", "float64", "B", "bwd_pkts / max(dur_sec, 0.001)", "Backward packet rate per second"),
    ("bidirectional_mean_piat_ms", "Flow IAT Mean", "float64", "B", "val * 1000.0", "Converted from ms to µs"),
    ("bidirectional_stddev_piat_ms", "Flow IAT Std", "float64", "B", "val * 1000.0", "Converted from ms to µs"),
    ("bidirectional_max_piat_ms", "Flow IAT Max", "float64", "A", "val * 1000.0", "Converted from ms to µs"),
    ("bidirectional_min_piat_ms", "Flow IAT Min", "float64", "A", "val * 1000.0", "Converted from ms to µs"),
    ("src2dst_duration_ms", "Fwd IAT Total", "float64", "B", "val * 1000.0", "Total forward duration in µs"),
    ("src2dst_mean_piat_ms", "Fwd IAT Mean", "float64", "B", "val * 1000.0", "Forward IAT mean in µs"),
    ("src2dst_stddev_piat_ms", "Fwd IAT Std", "float64", "B", "val * 1000.0", "Forward IAT std in µs"),
    ("src2dst_max_piat_ms", "Fwd IAT Max", "float64", "A", "val * 1000.0", "Forward IAT max in µs"),
    ("src2dst_min_piat_ms", "Fwd IAT Min", "float64", "A", "val * 1000.0", "Forward IAT min in µs"),
    ("dst2src_duration_ms", "Bwd IAT Total", "float64", "B", "val * 1000.0", "Total backward duration in µs"),
    ("dst2src_mean_piat_ms", "Bwd IAT Mean", "float64", "B", "val * 1000.0", "Backward IAT mean in µs"),
    ("dst2src_stddev_piat_ms", "Bwd IAT Std", "float64", "B", "val * 1000.0", "Backward IAT std in µs"),
    ("dst2src_max_piat_ms", "Bwd IAT Max", "float64", "A", "val * 1000.0", "Backward IAT max in µs"),
    ("dst2src_min_piat_ms", "Bwd IAT Min", "float64", "A", "val * 1000.0", "Backward IAT min in µs"),
    ("bidirectional_fin_packets", "FIN Flag Count", "int64", "A", "Direct 1:1", "Total packets with FIN flag"),
    ("bidirectional_syn_packets", "SYN Flag Count", "int64", "A", "Direct 1:1", "Total packets with SYN flag"),
    ("bidirectional_rst_packets", "RST Flag Count", "int64", "A", "Direct 1:1", "Total packets with RST flag"),
    ("bidirectional_psh_packets", "PSH Flag Count", "int64", "A", "Direct 1:1", "Total packets with PSH flag"),
    ("bidirectional_ack_packets", "ACK Flag Count", "int64", "A", "Direct 1:1", "Total packets with ACK flag"),
    ("bidirectional_urg_packets", "URG Flag Count", "int64", "A", "Direct 1:1", "Total packets with URG flag"),
    ("bidirectional_cwr_packets", "CWE Flag Count", "int64", "B", "Direct 1:1", "TCP CWR flag mapped to CWE flag count"),
    ("bidirectional_ece_packets", "ECE Flag Count", "int64", "A", "Direct 1:1", "Total packets with ECE flag"),
    ("src2dst_psh_packets", "Fwd PSH Flags", "int64", "A", "Direct 1:1", "Forward packets with PSH flag"),
    ("dst2src_psh_packets", "Bwd PSH Flags", "int64", "A", "Direct 1:1", "Backward packets with PSH flag"),
    ("src2dst_urg_packets", "Fwd URG Flags", "int64", "A", "Direct 1:1", "Forward packets with URG flag"),
    ("dst2src_urg_packets", "Bwd URG Flags", "int64", "A", "Direct 1:1", "Backward packets with URG flag"),
    ("window_packets", "tcp_flag_bitmask", "int64", "C", "Bitwise OR across flow", "Cumulative TCP control flag bitmask"),
    ("dst2src_packets, src2dst_packets", "Down/Up Ratio", "float64", "B", "bwd / max(fwd, 1)", "Bidirectional packet volume ratio"),
    ("window_packets", "TTL Mean", "float64", "C", "np.mean(ttls)", "Mean IP Time-To-Live across flow packets"),
    ("window_packets", "TTL Std", "float64", "C", "np.std(ttls)", "Standard deviation of IP Time-To-Live"),
    ("window_packets", "TTL Variance", "float64", "C", "ttl_std ** 2", "Variance of IP Time-To-Live"),
    ("window_packets", "TTL Min", "float64", "C", "np.min(ttls)", "Minimum IP Time-To-Live observed"),
    ("window_packets", "TTL Max", "float64", "C", "np.max(ttls)", "Maximum IP Time-To-Live observed"),
    ("window_packets", "TCP Window Size Init", "float64", "C", "first forward tcp_win", "Initial advertised TCP window size"),
    ("window_packets", "TCP Window Size Mean", "float64", "C", "np.mean(win_sizes)", "Mean advertised TCP window size"),
    ("window_packets", "IP Flags DF Count", "int64", "C", "sum(ip_df)", "Count of packets with Don't Fragment flag"),
    ("window_packets", "IP Flags MF Count", "int64", "C", "sum(ip_mf)", "Count of packets with More Fragments flag"),
    ("window_packets", "Retransmission Count", "int64", "C", "Duplicate seq tracking", "Number of duplicate TCP data/SYN transmissions"),
    ("window_packets", "Port Sequentiality Score", "float64", "C", "ratio |diff| == 1", "Sequential destination port scan metric (0.0 to 1.0)"),
    ("window_packets", "Port Access Type", "string", "C", "SEQUENTIAL / RANDOM / SINGLE", "Classification of port scanning behavior"),
]
